server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.30.144:3306/sync-tool?useSSL=false&autoReconnect=true&characterEncoding=utf8
    username: root
    password: 123456
  threads:
    virtual:
      enabled: true
  aot:
    enabled: true
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:./data/sync-tool;MODE=MySQL;DATABASE_TO_LOWER=TRUE
#    username: root
#    password: 123456
#    # 开启这个配置就可以通过 web 页面访问了，例如：http://localhost:8080/springboot-h2/h2-console
#    h2:
#      console:
#        enabled: true
#        settings:
#          # 开启h2 console 跟踪 方便调试  默认 false
#          trace: true
#          # 允许console 远程访问 默认false
#          web-allow-others: true
#          # h2 访问路径上下文
#          path: /h2-console
#  sql:
#    init:
##      data-locations: classpath:db/data.sql
#      platform: h2
#      schema-locations: classpath:db/sync-tool.sql
#      mode: always
#      continue-on-error: true
# mybatis-plus 配置
mybatis-plus:
#  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.script.local.mapper
  global-config:
    banner: false
  #原生配置
  configuration:
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志输出配置
logging:
  level:
    root: INFO
    org:
      springframework:
        security: WARN
        web: ERROR
  file:
    path: ./logs
    name: './logs/sync-tool.log'
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50}:%L - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50}:%L - %msg%n'
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.script.local.web
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true

  setting:
    language: zh_cn